version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "${PORT}"
        NAME: "${NAME}"
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      NAME: "${NAME}"
    restart: always
    volumes:
      - static:/usr/src/SocialNetwork/social_network/static
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  static:

networks:
  default:
    name: "${NAME}_network"
